version: "3.7"

services:
    mysql:
        build: "./10_mysql"
        #image: "my10_mysql"
        environment:
            MYSQL_DATABASE: "test"
            # So you don't have to use root, but you can if you like
            # MYSQL_USER: "root"
            # Password for root access
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        expose:
            # Opens port 3306 on the container
            - "3306"
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
        network_mode: "bridge"
    node:
        #image: my00_code
        build: "./00_mycode"
        restart: "always"
        ports:
            - "8089:8088"
        links:
            - "mysql"
        expose:
            - "8089"
        network_mode: "bridge"
 
# Names our volume
volumes:
    my-db: